name    'fewbytes/puppetmaster'
version '0.1.0'
source 'UNKNOWN'
author 'fewbytes'
license 'Apache License, Version 2.0'
summary 'Install/manage puppetmaster'
description 'Install/manage puppetmaster, installation from rubygems (for 1.9.1 support)'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/puppetdb'
dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/ruby'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'fewbytes/upstart'
